print("========================================")
print("      BCH ENTERPRISE VISITOR KIOSK      ")
print("========================================")
print ("What is your name?")
name=input()
print ("What is your email?")
email=input()
print ("What is your organization?")
Organization=input()
print ("What is your access level?")
Aclevel=input() 
prov="BCH SOFTWARE TERMINAL SYSTEM"
print ("+--------------------------------------------------+")
print ("|            Apex entertainment pass               |")
print ("|--------------------------------------------------|")
print ("| ATTENDEE : "+(name).ljust(38)+"|")
print ("| EMAIL : "+(email).ljust(41)+"|")
print ("| ORG : "+(Organization).ljust(43)+"|")
print ("| ACCESS LEVEL : "+(Aclevel).ljust(34)+"|")
print ("| PROVIDER : "+(prov).ljust(38)+"|")
print ("+--------------------------------------------------+")